routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => ['auth']], function () {
    Route::resource('ktp', 'KtpController');
    Route::get('/home', 'HomeController@index')->name('home');

});


Auth::routes();

app/Models/Ktp.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ktp extends Model
{
    protected $table = 'ktp';

    protected $fillable = [
            'nik',
            'nama',
            'tempat_lahir',
            'tanggal_lahir',
            'jenis_kelamin',
            'alamat',
            'rt',
            'rw',
            'desa',
            'kecamatan',
            'agama',
            'status_perkawinan',
            'pekerjaan',
            'kewarganegaraan',
            'berlaku_hingga',
    ];
}

app/Http/Controllers/API/KtpController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Resources\KtpCollection;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Ktp;

class KtpController extends Controller
{
    public $successStatus = 200;

    public function index()
    {
        $data = Ktp::orderBy('created_at','desc');
        if (request()->q != '') {
            $data = $data->where('nik', 'LIKE', '%' . request()->q . '%');
            $data = $data->orWhere('nama', 'LIKE', '%' . request()->q . '%');
        }
        $data = $data->paginate(10);
        return new KtpCollection($data);
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'nik' => 'required',
            'nama' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'alamat' => 'required',
            'rt' => 'required',
            'rw' => 'required',
            'desa' => 'required',
            'kecamatan' => 'required',
            'agama' => 'required',
            'status_perkawinan' => 'required',
            'pekerjaan' => 'required',
            'kewarganegaraan' => 'required',
            'berlaku_hingga' => 'nullable',
        ]);

        try {
            $requestData = $request->all();
            $store = KTP::create($requestData);
            return response()->json(['status' => 'success','data'=>$store]);
        } catch (\Exception $e) {
            return response()->json(['status' => 'failed']);
        }
    }


    public function show($id)
    {
        try {
            $data = Ktp::findOrFail($id);
            return response()->json(['status' => 'success','data'=>$data]);
        } catch (\Exception $e) {
            return response()->json(['status' => 'failed']);
        }
    }


    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nik' => 'required',
            'nama' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'alamat' => 'required',
            'rt' => 'required',
            'rw' => 'required',
            'desa' => 'required',
            'kecamatan' => 'required',
            'agama' => 'required',
            'status_perkawinan' => 'required',
            'pekerjaan' => 'required',
            'kewarganegaraan' => 'required',
            'berlaku_hingga' => 'nullable',
        ]);

        try {
            $requestData = $request->all();
            $data = Ktp::findOrFail($id);
            $data->update($requestData);
            return response()->json(['status' => 'success','data'=>$data]);
        } catch (\Exception $e) {
            return response()->json(['status' => 'failed']);
        }

    }

    public function destroy($id)
    {
        try {
            $destroy = Ktp::findOrFail($id);
            $destroy->delete();
            return response()->json(['status' => 'success']);
        } catch (\Exception $e) {
            return response()->json(['status' => 'failed']);
        }
    }
}

app/Http/Controllers/KtpController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ktp;
use Illuminate\Http\Request;


class KtpController extends Controller
{

    public function index()
    {
        $data = Ktp::get();
        return view('ktp.index', compact('data'));
    }

    public function create()
    {
        return view('ktp.create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'nik' => 'required',
            'nama' => 'required',
            'tempat_lahir'=> 'required',
            'tanggal_lahir'=> 'required',
            'jenis_kelamin'=> 'required',
            'alamat'=> 'required',
            'rt'=> 'required',
            'rw'=> 'required',
            'desa'=> 'required',
            'kecamatan'=> 'required',
            'agama'=> 'required',
            'status_perkawinan'=> 'required',
            'pekerjaan'=> 'required',
            'kewarganegaraan'=> 'required',
            'berlaku_hingga'=> 'nullable',
        ]);

        $requestData = $request->all();
        $store = KTP::create($requestData);
        return redirect(Route('ktp.index'))->with(['success' => 'KTP: ' . $store->name . ' ditambahkan']);
    }

    public function show($id)
    {

    }


    public function edit($id)
    {
        $edit = Ktp::find($id);
        return view('ktp.edit',compact('edit'));
    }


    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'nik' => 'required|max:12',
            'nama' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'jenis_kelamin' => 'required',
            'alamat' => 'required',
            'rt' => 'required',
            'rw' => 'required',
            'desa' => 'required',
            'kecamatan' => 'required',
            'agama' => 'required',
            'status_perkawinan' => 'required',
            'pekerjaan' => 'required',
            'kewarganegaraan' => 'required',
            'berlaku_hingga' => 'nullable',
        ]);
        $update = Ktp::find($id);
        $requestData = $request->all();
        $update->update($requestData);
        return redirect(Route('ktp.index'))->with(['success' => 'KTP: ' . $update->name . ' diperbaharui']);
    }


    public function destroy($id)
    {
        $destroy = Ktp::find($id);
        $destroy->delete();
        return redirect(Route('ktp.index'))->with(['success' => 'KTP: ' . $destroy->name . ' dihapus']);
    }
}

resources/views/ktp/create.blade.php
@extends('layouts.app');

@section('content')
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <a href="{{route('ktp.index')}}">Kembali</a>
        </div>
        <div class="col-12">
            <form class="row" method="POST" action="{{route('ktp.store')}}">
                @csrf
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">NIK</label>
                        {!! Form::text('nik', null, ['class'=>'form-control', 'placeholder'=>"Masukan NIK..."]) !!}
                        {!! $errors->first('nik', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Nama</label>
                        {!! Form::text('nama', null, ['class'=>'form-control', 'placeholder'=>"Masukan Nama..."]) !!}
                        {!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Tempat Lahir</label>
                        {!! Form::text('tempat_lahir', null, ['class'=>'form-control', 'placeholder'=>"Masukan Tempat Lahir..."]) !!}
                        {!! $errors->first('tempat_lahir', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Tanggal Lahir</label>
                        {!! Form::date('tanggal_lahir', null, ['class'=>'form-control', 'placeholder'=>"Masukan tanggal_lahir..."]) !!}
                        {!! $errors->first('tanggal_lahir', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Jenis Kelamin</label>
                        {!! Form::select('jenis_kelamin', ['L'=>'Laki-Laki','P'=>'Perempuan'], null, ['class'=>'form-control','placeholder'=>'Pilih Jenis Kelamin']) !!}
                        {!! $errors->first('jenis_kelamin', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Alamat</label>
                        {!! Form::textarea('alamat', null, ['class'=>'form-control', 'placeholder'=>"Masukan Alamat...",'rows'=>'3']) !!}
                        {!! $errors->first('alamat', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">RT</label>
                        {!! Form::text('rt', null, ['class'=>'form-control', 'placeholder'=>"Masukan rt..."]) !!}
                        {!! $errors->first('rt', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">RW</label>
                        {!! Form::text('rw', null, ['class'=>'form-control', 'placeholder'=>"Masukan RW..."]) !!}
                        {!! $errors->first('rw', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Desa</label>
                        {!! Form::text('desa', null, ['class'=>'form-control', 'placeholder'=>"Masukan Desa..."]) !!}
                        {!! $errors->first('desa', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Kecamatan</label>
                        {!! Form::text('kecamatan', null, ['class'=>'form-control', 'placeholder'=>"Masukan Kecamatan..."]) !!}
                        {!! $errors->first('kecamatan', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Agama</label>
                        {!! Form::select('agama', ['Islam'=>'Islam','Kristen Protestan'=>'Kristen Protestan','Katholik'=>'Katholik','Budha'=>'Budha','Konghucu'=>'Konghucu'], null, ['class'=>'form-control','placeholder'=>'Pilih Agama']) !!}
                        {!! $errors->first('agama', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Status Perkawinan</label>
                        {!! Form::select('status_perkawinan', ['Belum Nikah'=>'Belum Nikah','Menikah'=>'Menikah','Duda'=>'Duda','Janda'=>'Janda'], null, ['class'=>'form-control','placeholder'=>'Pilih Status Perkawinan']) !!}
                        {!! $errors->first('status_perkawinan', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Pekerjaan</label>
                        {!! Form::text('pekerjaan', null, ['class'=>'form-control', 'placeholder'=>"Masukan Pekerjaan..."]) !!}
                        {!! $errors->first('pekerjaan', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Kewarganegaraan</label>
                        {!! Form::select('kewarganegaraan', ['WNI'=>'WNI','WNA'=>'WNA'], null, ['class'=>'form-control','placeholder'=>'Pilih Kewarganegaraan']) !!}
                        {!! $errors->first('kewarganegaraan', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Berlaku Hingga</label>
                        {!! Form::date('berlaku_hingga', null, ['class'=>'form-control', 'placeholder'=>"Masukan Berlaku Hingga..."]) !!}
                        {!! $errors->first('berlaku_hingga', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/ktp/edit.blade.php
@extends('layouts.app');

@section('content')
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <a href="{{route('ktp.index')}}">Kembali</a>
        </div>
        <div class="col-12">
            <form class="row" method="POST" action="{{route('ktp.update',$edit->id)}}">
                @csrf
                @method('PUT')
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">NIK</label>
                        {!! Form::text('nik', $edit->nik, ['class'=>'form-control', 'placeholder'=>"Masukan NIK..."]) !!}
                        {!! $errors->first('nik', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Nama</label>
                        {!! Form::text('nama', $edit->nama, ['class'=>'form-control', 'placeholder'=>"Masukan Nama..."]) !!}
                        {!! $errors->first('nama', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Tempat Lahir</label>
                        {!! Form::text('tempat_lahir', $edit->tempat_lahir, ['class'=>'form-control', 'placeholder'=>"Masukan Tempat Lahir..."]) !!}
                        {!! $errors->first('tempat_lahir', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Tanggal Lahir</label>
                        {!! Form::date('tanggal_lahir', $edit->tanggal_lahir, ['class'=>'form-control', 'placeholder'=>"Masukan tanggal_lahir..."]) !!}
                        {!! $errors->first('tanggal_lahir', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Jenis Kelamin</label>
                        {!! Form::select('jenis_kelamin', ['L'=>'Laki-Laki','P'=>'Perempuan'], $edit->jenis_kelamin, ['class'=>'form-control','placeholder'=>'Pilih Jenis Kelamin']) !!}
                        {!! $errors->first('jenis_kelamin', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Alamat</label>
                        {!! Form::textarea('alamat', $edit->alamat, ['class'=>'form-control', 'placeholder'=>"Masukan Alamat...",'rows'=>'3']) !!}
                        {!! $errors->first('alamat', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">RT</label>
                        {!! Form::text('rt', $edit->rt, ['class'=>'form-control', 'placeholder'=>"Masukan rt..."]) !!}
                        {!! $errors->first('rt', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">RW</label>
                        {!! Form::text('rw', $edit->rw, ['class'=>'form-control', 'placeholder'=>"Masukan RW..."]) !!}
                        {!! $errors->first('rw', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Desa</label>
                        {!! Form::text('desa', $edit->desa, ['class'=>'form-control', 'placeholder'=>"Masukan Desa..."]) !!}
                        {!! $errors->first('desa', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Kecamatan</label>
                        {!! Form::text('kecamatan', $edit->kecamatan, ['class'=>'form-control', 'placeholder'=>"Masukan Kecamatan..."]) !!}
                        {!! $errors->first('kecamatan', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Agama</label>
                        {!! Form::select('agama', ['Islam'=>'Islam','Kristen Protestan'=>'Kristen Protestan','Katholik'=>'Katholik','Budha'=>'Budha','Konghucu'=>'Konghucu'], $edit->agama, ['class'=>'form-control','placeholder'=>'Pilih Agama']) !!}
                        {!! $errors->first('agama', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Status Perkawinan</label>
                        {!! Form::select('status_perkawinan', ['Belum Nikah'=>'Belum Nikah','Menikah'=>'Menikah','Duda'=>'Duda','Janda'=>'Janda'], $edit->status_perkawinan, ['class'=>'form-control','placeholder'=>'Pilih Status Perkawinan']) !!}
                        {!! $errors->first('status_perkawinan', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Pekerjaan</label>
                        {!! Form::text('pekerjaan', $edit->pekerjaan, ['class'=>'form-control', 'placeholder'=>"Masukan Pekerjaan..."]) !!}
                        {!! $errors->first('pekerjaan', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Kewarganegaraan</label>
                        {!! Form::select('kewarganegaraan', ['WNI'=>'WNI','WNA'=>'WNA'], $edit->kewarganegaraan, ['class'=>'form-control','placeholder'=>'Pilih Kewarganegaraan']) !!}
                        {!! $errors->first('kewarganegaraan', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label for="for">Berlaku Hingga</label>
                        {!! Form::date('berlaku_hingga', $edit->berlaku_hingga, ['class'=>'form-control', 'placeholder'=>"Masukan Berlaku Hingga..."]) !!}
                        {!! $errors->first('berlaku_hingga', '<p class="help-block">:message</p>') !!}
                    </div>
                </div>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/ktp/index.blade.php
@extends('layouts.app');

@section('content')
    <div class="row">
        <div class="col-12 mb-2 d-flex flex-row-reverse">
            <a href="{{route('ktp.create')}}" class="btn btn-primary">Tambah Data</a>
        </div>
        <div class="col-12">
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">NIK</th>
                        <th scope="col">Nama</th>
                        <th scope="col">Tempat/Tanggal Lahir</th>
                        <th scope="col">Jenis Kelamin</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                    <tbody>
                        @foreach ($data as $item)
                            <tr>
                                <th scope="row">{{$loop->iteration}}</th>
                                <td>{{$item->nik}}</td>
                                <td>{{$item->nama}}</td>
                                <td>{{$item->tempat_lahir.', '.$item->tanggal_lahir}}</td>
                                <td>{{$item->jenis_kelamin}}</td>
                                <td>
                                    <form action="{{route('ktp.destroy',$item->id)}}" method="POST" onsubmit="return ConfirmDelete()">
                                        @csrf
                                        @method('DELETE')
                                        <a href="{{route('ktp.edit',$item->id)}}" class="btn btn-link">Edit</a>
                                        <button class="btn btn-link">
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </table>
        </div>
    </div>
@endsection